### ISSUE TITLE
Support for HEIF & HEVC file formats on iOS

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/trigger.io-file#2]
Some capabilities that are not currently available to us that are needed to support HEIF & HEVC:

- [x] Conversion of HEIF files to JPEG
- [ ] Detect when a HEIF or HEVC file is selected
- [ ] UIImage support for HEIF files
- [ ] Safari support for embedding HEIF files

**Comment by prud** [comment]
@antoinevg As new iOS devices and versions are becoming the normal, we're getting more and more reports reg. this. Are you aware of any changes on Apple's side so that the app could better support those file types in the future?

Alternatively, could you advise on at least detecting this situation (file ending?) on our side so we could provide a specific error message in that case? Thank you very much! /cc

**Comment by prud** [comment]
@antoinevg We have now been able to reliably reproduce the issue with high efficiency images:

1. On an iOS 11 device, enable high efficiency file format in the camera settings
2. Capture a new photo with your device camera (ends up as .HEIC)
3. Open a Trigger.io-based app
4. Use forge.file.getImage() to get the previously taken photo from the camera
5. Upload the file object via forge.request.ajax() with fileUploadMethod=raw
--> Error

This issue does NOT happen when taking a new photo through the file module OR when selecting a previous image that is not .HEIC

Would it be possible to support this? As iOS 11 is becoming widely adopted, users are more and more expecting that this should work.

As an alternative, is there any chance that the error could at least be different, so that we could have a specialized handling / error message for this, e.g. advising the user to turn off high efficiently file format?

**Comment by antoinevg** [comment]
I haven't tried it, but it looks like you can at least disable HEIF in iOS using for e.g.

https://petapixel.com/2017/09/25/make-iphone-shoot-jpegs-ios-11/

**Comment by antoinevg** [comment]
First-order HEIF support slated for release in Forge Platform `v2.7` on both Android and iOS:

* Images accessed through `forge.file.*` API's will always return a JPEG image to user code irrespective of their source format.

Things that are still going to need more work from Google && Apple before we can support them:

* Rendering of HEIF images in Android or iOS WebViews (See https://github.com/nokiatech/heif/wiki/IV.-HEIF-Reader-JavaScript-Implementation for interim support via Javascript rendering)
* Accessing the original HEIF image from Javascript.
